### ISSUE TITLE
bug: not advertising some capabilities that are supported

### ISSUE THREAD

**Issue by pnadolny13** [danielptv/tap-db2#13]
I noticed that the default capabilities are being overridden here https://github.com/danielptv/tap-db2/blob/fd6eb0da39004b63d7a359a157eedb5c1ae5708e/tap_db2/tap.py#L134. Is there a reason for that? I think that tap supports capabilities that its not advertising: about, catalog, discover. Tools like Meltano use these capabilities to decide how to run the tap (i.e. run discover before syncing).

Does this also support state?

**Comment by danielptv** [comment]
You are correct, this was a mishap on my part. Should be fixed now.
The tap does indeed support state.
